### PR TITLE
Singleton/Static Library Experiment

### PR DESCRIPTION
**Pull request by alexhauser**
@josegomez, this is an experiment I started when noticing that we are passing around `sqrlInstance` variables between our ViewModels, and I was wondering whether this could be avoided.

Almost all of the library's functionality can be offered statically, with the only exception being the CPS server. So I did the following:
 
- Declare all the methods `static`, so that they can be used without a class instance, e.g. `SQRL.GenerateIdentityBlock1(...)`
- Convert the class to use the singleton pattern, so that only one instance of the class can exist at any point in time (this should be helpful, since the CPS server must not be started multiple times anyway)
- Removed all `sqrlInstance` variables from our view models 
- Refactored the code to use the static library methods instead
- Only instanciate the SQRL library in the `AuthenticationViewModel`, where the CPS server is actually used

This has several advantages:
- It de-clutters and simplifies the ViewModel code, since we don't have to pass around and deal with libarary instances
- Eliminates the need for overloaded constructors in most of the ViewModels.
- Starts the CPS server only when it is actually being used (upon authentication)

Since this is a somewhat mayor shift in how the library is used, I wanted to discuss this with you and get your opinion. I am in no way insisting in merging this PR, I just wondered if it could be done and how it would benefit the overall appearance of our code. As you can see in the number of additions vs. deletions, this should be a net win in terms of code clarity. But it's a matter of taste, too.

What's your take on this, @josegomez?

### CODE REVIEW

**Review by josegomez — APPROVED** [review]
Looks great

**Comment by josegomez** [comment]
This is great @alexhauser something I had in my todo too, I started with an instance class and well down the rabbit hole we went. But I agree it would have been better to go this route. 
Great job

**Comment by josegomez** [comment]
One thing we need to do when we merge this is change the ReadMe Documentation to reflect these changes. I'll open an issue for that.

**Comment by alexhauser** [comment]
@josegomez, I'm out in the fields with the kids, but if you want to merge this one yourself so that you can continue working, please go ahead!

**Pull request merged**
