### PR TITLE
WIP: Add Github CI

### PR DESCRIPTION
**Pull request by alexhauser**
Add a workflow for using Github's continuous integration feature. This may need additional changes, we'll see after the first run.

### CODE REVIEW

**Comment by alexhauser** [comment]
Ok, so the CI build is failing because of that irritating `PackageLicenseUrl` error which also pops up every so often on my local builds.

Going to look at this more closely, so please don't merge yet.

**Comment by alexhauser** [comment]
Ok, removing `<PackageLicenseFile>` from `SQRLUtilsLib.csproj` got rid of the `PackageLicenseUrl` error.

Now getting another one, this time it seems to affect the Sodium project:

>/opt/hostedtoolcache/dncs/3.1.100/x64/sdk/3.1.100/Sdks/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props(208,3): 

>error MSB4019: The imported project "/opt/hostedtoolcache/dncs/3.1.100/x64/sdk/3.1.100/Sdks/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.WinFX.props" was not found. Confirm that the expression in the Import declaration "Microsoft.WinFX.props" is correct, and that the file exists on disk. 

>/home/runner/work/SQRLDotNetClient/SQRLDotNetClient/Sodium.Core/Sodium.Core.ForSqrl.csproj

It might be because I'm pulling in .NET Core 3.1.1 for the CI build, and the sodium project needs a different SDK version, or those specific tools mentioned in the error message are missing in the newer version. 

The Sodium project file says:

`<Project Sdk="MSBuild.Sdk.Extras/2.0.54">` and
`<TargetFrameworks>Xamarin.iOS10;netstandard1.6;netstandard2.0</TargetFrameworks>`

I don't know. I don't have too much experience with those kinds of things. Do you have an idea, @josegomez? Shall we try to bring everything up to 3.1.1?

**Comment by josegomez** [comment]
So you want to use the CI to automatically run tests?

**Comment by alexhauser** [comment]
Yes, sorry for not making that clear from the beginning. Automatically running tests is the main reason (and the end goal) for this PR, but it would generally be nice to see if something that is pushed upstream breaks anything.

**Comment by josegomez** [comment]
ok so the issue here is particular to sodium core, because it targets multiple platoforms among them a few that linux does't recognize. The fix IMO is to remove those extra targets since we only care about core, let me see if I can make that work.

Otherwise, we just need to remove sodium.core from the automatic build since the other projects use a nuget anyways.

**Comment by josegomez** [comment]
Looks like we can change the target of sodium to be core instead of netstandard.... Need to test... but it builds...

**Comment by alexhauser** [comment]
Sounds good! Plmk if I can do anything to assist.

Btw, I've created the CI branch directly on this repo instead of on my fork, so you can easily push to it if you want.

**Comment by josegomez** [comment]
Kewl all checks pass, and the CI ran ok. We need to modify it to actually run the tests I suspect but we are good to go.

**Pull request merged**
