### PR TITLE
Add PDF support

### LINKED ISSUE #72: Add PDF support
Add support for exporting the textual identity as well as the rescue code to a PDF file.

Progress:
- [x] Identity
- [ ] Rescue Code (implemented core functionality but not exposed in the UI yet)

I'm going for this one next, @josegomez!

### PR DESCRIPTION
**Pull request by alexhauser**
Closes #72.

### Description:
This adds support for creating PDF documents for storing/printing a backup of both identity (textual version + QR-Code) as well as the rescue code.

Here are two sample documents:

[RescueCodeTest.pdf](https://github.com/sqrldev/SQRLDotNetClient/files/4466706/RescueCodeTest.pdf)
[IdentityTest.pdf](https://github.com/sqrldev/SQRLDotNetClient/files/4466707/IdentityTest.pdf)

documents

### Implementation:
A new class `PdfHelper` offers static methods for creating the PDF documents. Here is some sample code:

```C#
string fileName = "Test.pdf";

PdfHelper.CreateRescueCodeDocument(fileName, "1234-5678-9012-3456-7890", "AlexDev1");
PdfHelper.CreateIdentityDocument(fileName, _identityManager.CurrentIdentity)
```

### Notes:
Even though "rescue code document"-creation functionality is already there, I have not yet made use of it in the current UI flow, since there is currently no common ground between the places that need it. This still needs some discussion.

Identity PDF export is already implemented in the export view, which I've shuffled around a bit to accomodate for the new functionality.

Also, I have fixed a few things along the way, most importantly:
-  Identity textual export as well as qr-code were both using the full identity instead of just block 2+3 (For convenience, I've added two optional parameters to `SQRLIdentity.ToByteArray()` to accomodate for this, the new signature now looks like this: `public byte[] ToByteArray(bool includeHeader = true, bool minimumSize = false)` 
-  Fixed a security issue where a temporary bitmap file was saved in the file system for displaying the qr code in the export view, but it was never removed. I changed the corresponding code to write to a `MemoryStream` instead.

### CODE REVIEW

**Review by josegomez — APPROVED** [review]
Great work

**Comment by josegomez** [comment]
Looks great! Merge away!

**Comment by alexhauser** [comment]
@josegomez, could you please test the PDF identity export on MacOS for me, since I don't have a testing environment set up? Thanks!

Getting all of this to work flawlessly on Linux was a bit of a struggle, so I am a little sceptic when it comes to the Mac.

**Comment by josegomez** [comment]
ok @alexhauser  testing now. What PDF Library did you use (out of curiosity)

**Comment by josegomez** [comment]
@alexhauser  works great!

**Comment by josegomez** [comment]
image

**Comment by alexhauser** [comment]
Cool, thanks @josegomez!

Well, the PDF library was a problem. There are simply no free/open source libraries that support .NET Core. I spent A LOT of time researching. 

I ended up using SkiaSharp, which is Microsoft's wrapper around Google's Skia 2d drawing/imaging library that is being used for Mono (Avalonia uses it too, btw.)

**Pull request merged**
