### PR TITLE
SQRL Platform Aware Installer

### PR DESCRIPTION
**Pull request by josegomez**
This is a branch to develop the Installer for SQRL. Using Avalonia UI, it should be platform aware and provide the same install / un-install experience for all Platforms.

For Issue #24

### CODE REVIEW

**Comment by alexhauser** [comment]
@josegomez, you could consider rebasing instead of merging changes happening in master, which should avoid cluttering up your PR with unrelated commits.

Also, I know it's only for testing the installer, but I thought I might still mention that the pre-release Winx64 version crashes upon opening identity settings. We'll have to investigate what causes this.

Cheers, Alex

**Comment by josegomez** [comment]
@alexhauser  I did do a re-base but I'm not sure why it did this I'm using the VIsual Studio Github tools and sometimes they can be funky.
Or maybe I'm doing it wrong, how do you rebase on your VS?
image


This is what I did, I suppose I could use the command line tools, Interesting that the win 64 crahes, it shouldn't... It works fine for me I'll double check that.

**Comment by josegomez** [comment]
Hmm @alexhauser 
Application: SQRLDotNetClientUI_win64.exe
CoreCLR Version: 4.700.19.56402
.NET Core Version: 3.1.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'System.Runtime.Serialization.Formatters.Binary.Converter' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
File name: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.Runtime.Serialization.Formatters.Binary.Converter..cctor()

Oddly enough the Debug Version works fine... Strange, maybe I need to add that library to the "trimmed" output package.

**Comment by alexhauser** [comment]
> Or maybe I'm doing it wrong, how do you rebase on your VS?

@josegomez, I don't use the builtin git stuff in VS at all, I use Github Desktop for all the standard tasks like pulling, pushing, changing branches etc., and the command line for tasks like rebasing etc. Lately, I find myself using the console more and more. It's just faster once you're comfortable with it.

In your case, I would have switched to the PlatformInstaller branch and typed a `git rebase master` into the console.

**Comment by josegomez** [comment]
Got it , yeah I'll try that next time, sorry about that. I love the console too bit it is easy sometimes to get comfortable inside Visual Studio just clicking a few buttons here and there.

**Comment by alexhauser** [comment]
> Oddly enough the Debug Version works fine... Strange, maybe I need to add that library to the "trimmed" output package.

Yeah, looks like a build/publishing issue rather than a coding issue. We'll figure it out!

**Comment by josegomez** [comment]
> Also, I know it's only for testing the installer, but I thought I might still mention that the pre-release Winx64 version crashes upon opening identity settings. We'll have to investigate what causes this.
> 
> Cheers, Alex

@alexhauser  this is fixed now, the issue was that the Clone() operation in IdentitySettings uses Serialization which in turn uses Reflection to load mscorlib (in Windows)
Because it uses reflection to do this, dotnet doesn't know that file is needed, so when I build the Self Contained Executable that file is left out. 
I've updated the project to force mscorelib to be included and not "trimmed" and re-uploaded the Windows Release.
Should be good to go.

**Comment by josegomez** [comment]
Not ready to merge yet (working on nix and mac) but if you got some time, can you check out / run this and see if it makes sense @alexhauser ?
I'll throw the executable in Release 1 for you to play with if you'd like.

**Comment by josegomez** [comment]
Installer Binary Uploaded to : https://github.com/sqrldev/SQRLDotNetClient/releases/download/v0.1-alpha/SQRLPlatformAwareInstaller.exe

It uses the github API to pull the different releases and download install the appropriate stuff.

**Comment by alexhauser** [comment]
> ...can you check out / run this and see if it makes sense @alexhauser ?

Sure, will take a look tomorrow morning!

**Comment by alexhauser** [comment]
@josegomez, just checked out the installer on Windows, and it worked like a charm! Great work!
Looking forward to seeing how it works once there are more releases published.

Here are some things that I've noticed/wondered:

- The installer should probably detect and warn if another application has already registered the `sqrl://` protocol handler. In my case, I had the GRC client installed, and it's handler just got silently overwritten.
- We should definitely add unistall support.
- Some UI elements could use a little more breathing room/margin, but I guess the UI/UX of the whole project will need some attention later anyway.
- Is the installer handling version upgrades properly already?

Again, great work, Jose!

**Comment by josegomez** [comment]
@alexhauser 
I'll see what I can do about detecting other clients, that shouldn't be too hard since the registry keys would be present, I can provide a warning.
Uninstall support is in the works
Yeah the UI is meh, I suck at it haha I'll re-shuffle some things

It does updates as much as if you run the installer again and thre is a new release you can install / override the old version. It doesn't do automatic updates that's a tough one because of the different systems and architectures I'm not sure how to approach it.
I think the auto-update mechanism will have to be in the Client itself and not the installer just because you'd never launch the Installer again and I supose we could create some sort of Task that automatically runs and checks but I'm not certain how well that would work.

If we make the AutoUpdate part of the regular client that would work better because every time the client is used it could check for updates, however in my experience it is tricky you download a new executable that somehow needs to replace itself, and there are permissions issues etc...

Certainly something to consider but maybe for now the installer can do the updates manually and maybe we can make the Client just "check" and let someone know hey there's an update, run the installer to get it?

IDK.. thoughts?

**Comment by alexhauser** [comment]
@josegomez, thanks for the update, I can see that we're on the same page on most points.

I agree that the "new version check" must be in the client, not in the installer.
How about if the installer copies itself into the programs dir on the first installation alongside with the client. Then, if the client detects a new version, it just fires up the installer with some arguments telling it to go directly to the version selection screen and preselect the latest version. Something like that. If we would like to get fancy, we could even have the client update the installer if necessary.

Regarding client update, I think the only thing that's important there is the db migration stuff, and I will look into that asap with the identity management project.

Cheers, Alex

**Comment by josegomez** [comment]
All right I think this is feature complete maybe. It was a lot of work, when you get a chance check it out @alexhauser  and let me know if something major is missing from it.
It downloads the latest release from github using the github API for each platform
For MAC it creates an Application Bundle and registers the URL handler
For Linux it creates a Desktop Application and copies the application and it's handler registration to all the "right" places
For Windows it downloads the Client and Registers the URL Scheme Handler

**Comment by josegomez** [comment]
PS: I did a rebase to get your latest changes and that worked but it still shows all the commits here (sorry) all the work I did is in the Installer Project so you may ignore everything else.

Once we marge we can compile the Installer and Publish it for each platform along with a new Release of the Client.

**Review by alexhauser — APPROVED** [review]
Really nice to see the installer supporting all 3 platforms now, great job @josegomez! 

I've really only very superficially skimmed the code since I have little time at the moment. I've found a few things like hardcoded strings, some redundand code etc., but no biggies at all, and we can improve those things later as we go along.

So please go ahead and merge, I will look at the installer more closely if I have time.

Again, very cool stuff, Jose!

**Comment by alexhauser** [comment]
@josegomez, one thing I've just noticed while running the installer on Windows:

When launching it within Visual Studio (elevated), the installer crashes after downloading the executable with a `System.InvalidOperationException: "Call from invalid thread"`.

If I run detached from Visual Studio, it shows the last screen for a second or two and then crashes, too. Don't know what's going on there, maybe you do though.

**Comment by josegomez** [comment]
> @josegomez, one thing I've just noticed while running the installer on Windows:
> 
> When launching it within Visual Studio (elevated), the installer crashes after downloading the executable with a `System.InvalidOperationException: "Call from invalid thread"`.
> 
> If I run detached from Visual Studio, it shows the last screen for a second or two and then crashes, too. Don't know what's going on there, maybe you do though.

Hmm I'll check it out.

**Comment by josegomez** [comment]
Got it, cross thread MessageBox because I'm trying to detect existing SQRL invokation protocol and warn the user... Have to Invoke that message from the right Thread.
image

**Comment by josegomez** [comment]
OK that issue is fixed. I'll Merge once it's done running the tests. Then I'll re-base the Mac specific URL fix and that will be ready to merge too

**Pull request merged**
