### PR TITLE
Update installer before installing update (and other stuff)

### LINKED ISSUE #197: Update Installer before Installing Update
Because the Installer / Updater is included in the zip file with the latest version of the software. When an update is detected, the OLD installer is used to install the latest update (and update the installer)

The issue there is that if there are changes in the new installer that we need applied that won't happen until the next time the installer/updater is run.

We need to find a way to FIRST update the installer/updater before we get and install the latest updates.

Here's my Proposal:
This won't fix the next update for the reasons stated above but it should fix any issues going forward and it doesn't require a whole new program or changes to the Client itself.

The installer today downloads the latest release in a zip file which contains a newer copy of the installer itself.

My proposal is to keep the mechanism as is until that point then change the behavior as follows:

- Installer downloads the latest Zip (as it does today)
- Extract the new Installer from that latest Zip and copy it to %TEMP%
- Then the old installer Process Starts the new installer and passes in:
- the current Install Location (if available) as a param
- the location of the downloaded zip (so we don't download it again) as a param
- and a flag to indicate that it should pick up where it left off
- old installer closes and lets the new installer pick up where it left off (extracting the zip file and doing the install logic)

So basically all it  just uses the old installer to download the newer copy (along with the update as it does today) but then allows the new (better) version to do the actual install.

One advantage of doing it this way is that we don't end up having to download the update multiple times, or separately download the installer which is a self contained executable which would double our download size and time.

Thoughts? or other options are welcome.

### PR DESCRIPTION
**Pull request by alexhauser**
Closes #197.

First of all, I need to apologize for the rediculous size and scope of this PR. Some of the changes I wanted to implement required refactoring on project level, and since there was nothing else being worked on at the moment, I just followed through. I know this makes reviewing this one a nightmare, but I hope it will be worth it.

### Descripton:
This PR implements the following open issues:

- Update Installer before installing update 
(the client now downloads the update archive and extracts and consequently launches the new installer, passing in the path to the update package, the version and the install path)
- Move log files into userspace

Tested on Windows and Linux, macOS currently untested because my Catalina VM is acting up.

Other changes:

- Rename `SQRLCommonUI` project to `SQRLCommon`, since the days where we only shared UI stuff is long past ;-)
- Remove the `GithubAPI` project and move the `GithubHelper` and `GithubRelease` classes to `SQRLCommon`, because I was getting into "circular dependency" territory
- Move parts of the client's local `Util` class to the new `CommonUtils` class within the `SQRLCommon` project, so that it can be shared among client and installer
- When downloading the list of releases from Github, this list is now stored in %TEMP% and can be read later instead of having to go online again
- Add `-v` / `-version` command line argument for the installer, which is used in combination with the `-a Update` action to pre-select the correct release in the UI when installing a pre-downloaded update package
- `PathConf` now holds the logging path as well
- Changed the way to enable "testing mode" in the installer, since the approach with placing a file in the executable directory didn't work reliably with the `/p:PublishSingleFile=true` option we use for the Installer. Instead, we're using an environment variable `SQRL_TESTMODE` now. Also, you can click the version label in the installer main screen 5 times now to enable testing mode.

### CODE REVIEW

**Review by josegomez — APPROVED** [review]
Lot's of changes but over-all it looks great. Thanks for your work @alexhauser  I'll do some playing around but it looks solid. 
I like the re-org too makes a lot more sense.

**Comment by josegomez** [comment]
Merge away this looks great! Thanks!

**Comment by alexhauser** [comment]
@josegomez, I think we might have a problem on macOS with this one, but my VM keeps acting up so I can't test properly atm. I will merge now, but we definitely need to do some more testing before publishing.

**Comment by josegomez** [comment]
ok @alexhauser  I'll try to test on the VM. 
Anything special I need to do to test it?

**Comment by alexhauser** [comment]
@josegomez, I had troubles even running the Installer on macOS, but my System Preferences Panel keeps failing to load the Security page. But I guess we might have a permissions/sandbox issue on macOS.

**Pull request merged**
