### PR TITLE
Add support for "test releases"

### PR DESCRIPTION
**Pull request by alexhauser**
### Description:

This adds support for "test releases" by having the Github helper check for a defined test keyword in release tags and omit releases containing this keyword if the "magic file" isn't present in the executable directory.

The current testing keyword for a release tag is: "**test**"
The current magic file name for switching to testing mode is: "**TESTING**"

This should help us with release testing.
Thoughts, @josegomez?

### CODE REVIEW

**Comment by alexhauser** [comment]
@josegomez, I forgot to mention that at the moment we obviously have a chicken-and egg problem with this method. The current client and installer don't know anything about test releases, so the next release will be "public" no matter what. But once everyone is on this next release, this system should provide us with some flexibility in release testing.

**Review by josegomez — APPROVED** [review]
Very nice merge away!

**Comment by josegomez** [comment]
@alexhauser one thing I just thought of, it may be worth it (though it can be a different PR) to adjust the client installer UI to allow you to take in pre-releases (for a testing group)

Think Production releases automatically for All
For development we put out test releases
But perhaps we have a Pre-Release check or checkbox to allow the general public to take in Alpha / Beta releases.

Not sure if it's worth the hassle just thinking aloud.

**Comment by alexhauser** [comment]
Very good point @josegomez, I like the idea!
Should be relatively easy to implement, too. I'll create a new PR for it.

**Pull request merged**
