### PR TITLE
Add client documentation

### LINKED ISSUE #22: Add documentation
**Description:**

Add XML documentation to the following parts of the project's codebase:

- [x] Library (done)
- [x] Client (done)
- [x] Installer (done)

### PR DESCRIPTION
**Pull request by alexhauser**
Closes #22.

### Description:
This adds code documentation to the client project. We should now have all three major parts of this project (library, client and installer) decently documented.

### CODE REVIEW

**Comment by josegomez** [comment]
👏👏🙌 nice job

**Comment by alexhauser** [comment]
You didn't approve @josegomez, are you still reviewing or can I merge?

**Comment by josegomez** [comment]
Sorry fat finger merge away

**Comment by josegomez** [comment]
It doesn’t give me the option on the phone go ahead merge! Thanks

**Pull request merged**
